version: "3"

services:
  jupyterlab:
    build: "."
    ports:
      - 8888:8888
    volumes:
      - type: bind
        source: "."
        target: /home/jovyan/work
    environment:
      NB_UID: 1000
      NB_GID: 100
      JUPYTER_ENABLE_LAB: "yes"
